name: Trigger auto deployment for readyup

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/readyup-AutoDeployTrigger-caeacb5f-1c97-4710-88f0-8e5a454d04d0.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.READYUP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.READYUP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.READYUP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.READYUP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.READYUP_REGISTRY_PASSWORD }}
          containerAppName: readyup
          resourceGroup: readyup_group
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


